/* eslint-disable prettier/prettier */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable prettier/prettier */

import { Hours, Minutes } from "src/types";

// Conversion constants
const MILLISECONDS_PER_MINUTE = 60 * 1000;
const MILLISECONDS_PER_HOUR = 60 * 60 * 1000;

export const MinutesToMilliseconds: { [key in Minutes]: number } = {
    [Minutes.ONE_MINUTES]: 1 * MILLISECONDS_PER_MINUTE,
    [Minutes.TWO_MINUTES]: 2 * MILLISECONDS_PER_MINUTE,
    [Minutes.FIVE_MINUTES]: 5 * MILLISECONDS_PER_MINUTE,
    [Minutes.TEN_MINUTES]: 10 * MILLISECONDS_PER_MINUTE,
    [Minutes.FIFTEEN_MINUTES]: 15 * MILLISECONDS_PER_MINUTE,
    [Minutes.TWENTY_MINUTES]: 20 * MILLISECONDS_PER_MINUTE,
    [Minutes.TWENTY_FIVE_MINUTES]: 25 * MILLISECONDS_PER_MINUTE,
    [Minutes.THIRTY_MINUTES]: 30 * MILLISECONDS_PER_MINUTE,
    [Minutes.THIRTY_FIVE_MINUTES]: 35 * MILLISECONDS_PER_MINUTE,
    [Minutes.FORTY_MINUTES]: 40 * MILLISECONDS_PER_MINUTE,
    [Minutes.FORTY_FIVE_MINUTES]: 45 * MILLISECONDS_PER_MINUTE,
    [Minutes.FIFTY_MINUTES]: 50 * MILLISECONDS_PER_MINUTE,
    [Minutes.FIFTY_FIVE_MINUTES]: 55 * MILLISECONDS_PER_MINUTE,
    [Minutes.SIXTY_MINUTES]: 60 * MILLISECONDS_PER_MINUTE,
    [Minutes.INGORE]: 0
};

export const HoursToMilliseconds: { [key in Hours]: number } = {
    [Hours.ZERO_HOUR]: 0 * MILLISECONDS_PER_HOUR,
    [Hours.ONE_HOUR]: 1 * MILLISECONDS_PER_HOUR,
    [Hours.TWO_HOUR]: 2 * MILLISECONDS_PER_HOUR,
    [Hours.THREE_HOUR]: 3 * MILLISECONDS_PER_HOUR,
    [Hours.FOUR_HOUR]: 4 * MILLISECONDS_PER_HOUR,
    [Hours.FIVE_HOUR]: 5 * MILLISECONDS_PER_HOUR,
    [Hours.SIX_HOUR]: 6 * MILLISECONDS_PER_HOUR,
    [Hours.SEVEN_HOUR]: 7 * MILLISECONDS_PER_HOUR,
    [Hours.EIGHT_HOUR]: 8 * MILLISECONDS_PER_HOUR,
    [Hours.NINE_HOUR]: 9 * MILLISECONDS_PER_HOUR,
    [Hours.TEN_HOUR]: 10 * MILLISECONDS_PER_HOUR,
    [Hours.ELEVEN_HOUR]: 11 * MILLISECONDS_PER_HOUR,
    [Hours.TWELVE_HOUR]: 12 * MILLISECONDS_PER_HOUR,
    [Hours.THIRTEEN_HOUR]: 13 * MILLISECONDS_PER_HOUR,
    [Hours.FOURTEEN_HOUR]: 14 * MILLISECONDS_PER_HOUR,
    [Hours.FIFTEEN_HOUR]: 15 * MILLISECONDS_PER_HOUR,
    [Hours.SIXTEEN_HOUR]: 16 * MILLISECONDS_PER_HOUR,
    [Hours.SEVENTEEN_HOUR]: 17 * MILLISECONDS_PER_HOUR,
    [Hours.EIGHTEEN_HOUR]: 18 * MILLISECONDS_PER_HOUR,
    [Hours.NINETEEN_HOUR]: 19 * MILLISECONDS_PER_HOUR,
    [Hours.TWENTY_HOUR]: 20 * MILLISECONDS_PER_HOUR,
    [Hours.TWENTY_ONE_HOUR]: 21 * MILLISECONDS_PER_HOUR,
    [Hours.TWENTY_TWO_HOUR]: 22 * MILLISECONDS_PER_HOUR,
    [Hours.TWENTY_THREE_HOUR]: 23 * MILLISECONDS_PER_HOUR,
    [Hours.INGORE]: 0
};