services:
  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"

  server:
    depends_on:
      - redis
    image: timely-server:latest
    container_name: timely-server
    restart: always
    ports:
      - "3000:3000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_URL: "mongodb+srv://timely:timely@cluster0.jzczfpq.mongodb.net/"
      PRIVATE_KEY: "0x3d4f4daa3742a4ac9c04c0c2108f47f166db10631b2a5094530a620b949197cc"
      PORT: 80

volumes:
  redis-data:
    external: false